// DateField names need to be null, all other can be ''
const initialValues = {
  knownContact: '',
  contactId: '',
  reportingJurisdiction: '',
  reportingHealthDept: '',
  caseStateLocalId: '',
  CDC2019nCoVID: '',
  NNDSSCaseId: '',
  interviewerFirstName: '',
  interviewerLastName: '',
  interviewerAffiliationOrganization: '',
  interviewerTelephone: '',
  interviewerEmail: '',
  currentStatus: '',
  testingStatus: '',
  puiReportDate: null,
  state: '',
  caseReportDate: null,
  county: '',
  dateOfBirth: null,
  ethnicity: '',
  age: '',
  ageUnits: '',
  race: '',
  sex: '',
  otherRace: '',
  positiveSpecimenCollected: '',
  firstPositiveSpecimenDate: null,
  firstPositiveSpecimenDateUnknown: '',
  pneumonia: '',
  acuteRespiratoryDistressSyndrome: '',
  anotherDiagnosisEtiology: '',
  abnormalChestXray: '',
  hospitalized: '',
  admissionDate: null,
  admissionDateUnknown: '',
  dischargeDate: null,
  dischargeDateUnknown: '',
  dischargeDateNotApplicable: '',
  intensiveCareUnit: '',
  mechanicalVentilationIntubation: '',
  totalDaysWithMV: '',
  ecmo: '',
  death: '',
  deathDate: null,
  deathDateUnknown: ''
};

export default initialValues;
